close all;clear all;clc;
numPoints  = 1e6;
normalDist = sort(normrnd(0, 1, numPoints, 1));
%% Weibull distributions
figure(1)
subplot(3,2,1);
weibullDistA = sort(wblrnd(1, 0.1, numPoints, 1));
axh1 = axis();
h1wbl  = plot(weibullDistA, normalDist,'b-','linewidth',2.0);
%set(axh1, 'FontSize', 18);
subplot(3,2,2);
weibullDistA = sort(wblrnd(1, 0.5, numPoints, 1));
axh2 = axis();
h2wbl  = plot(weibullDistA, normalDist,'b-','linewidth',2.0);
%set(axh2, 'FontSize', 18);
subplot(3,2,3);
weibullDistA = sort(wblrnd(1, 1, numPoints, 1));
axh3 = axis();
h3wbl  = plot(weibullDistA, normalDist,'b-','linewidth',2.0);
%set(axh3, 'FontSize', 18);
subplot(3,2,4);
weibullDistA = sort(wblrnd(1, 5, numPoints, 1));
axh4 = axis();
h4wbl  = plot(weibullDistA, normalDist,'b-','linewidth',2.0);
%set(axh4, 'FontSize', 18);
subplot(3,2,5);
weibullDistA = sort(wblrnd(1, 25, numPoints, 1));
axh5 = axis();
h5wbl  = plot(weibullDistA, normalDist,'b-','linewidth',2.0);
%set(axh5, 'FontSize', 18);
subplot(3,2,6);
weibullDistA = sort(wblrnd(1, 50, numPoints, 1));
axh6 = axis();
h6wbl  = plot(weibullDistA, normalDist,'b-','linewidth',2.0);
%set(axh6, 'FontSize', 18);
clearvars weibullDistA;
%% Rayleigh distribution
figure(2)
subplot(2,2,1);
axh1 = axis();
rayleighDistA = sort(raylrnd(0.25, numPoints, 1));
h1rayl  = plot(rayleighDistA, normalDist,'b-','linewidth',2.0);
%set(axh1, 'FontSize', 18);
subplot(2,2,2);
axh2 = axis();
rayleighDistA = sort(raylrnd(0.5, numPoints, 1));
h2rayl  = plot(rayleighDistA, normalDist,'b-','linewidth',2.0);
%set(axh2, 'FontSize', 18);
subplot(2,2,3);
axh3 = axis();
rayleighDistA = sort(raylrnd(1, numPoints, 1));
h3rayl  = plot(rayleighDistA, normalDist,'b-','linewidth',2.0);
%set(axh3, 'FontSize', 18);
subplot(2,2,4);
axh4 = axis();
rayleighDistA = sort(raylrnd(5, numPoints, 1));
h4rayl  = plot(rayleighDistA, normalDist,'b-','linewidth',2.0);
%set(axh4, 'FontSize', 18);
clearvars rayleighDistA;
%% Chi-Square distribution
figure(3)
subplot(3,2,1);
axh1 = axis();
chi2DistA = sort(chi2rnd(1, numPoints, 1));
h1chi2  = plot(chi2DistA, normalDist,'b-','linewidth',2.0);
%set(axh1, 'FontSize', 18);
subplot(3,2,2);
axh2 = axis();
chi2DistA = sort(chi2rnd(2, numPoints, 1));
h2chi2  = plot(chi2DistA, normalDist,'b-','linewidth',2.0);
%set(axh2, 'FontSize', 18);
subplot(3,2,3);
axh3 = axis();
chi2DistA = sort(chi2rnd(3, numPoints, 1));
h3chi2  = plot(chi2DistA, normalDist,'b-','linewidth',2.0);
%set(axh3, 'FontSize', 18);
subplot(3,2,4);
axh4 = axis();
chi2DistA = sort(chi2rnd(4, numPoints, 1));
h4chi2  = plot(chi2DistA, normalDist,'b-','linewidth',2.0);
%set(axh4, 'FontSize', 18);
subplot(3,2,5);
axh5 = axis();
chi2DistA = sort(chi2rnd(10, numPoints, 1));
h5chi2  = plot(chi2DistA, normalDist,'b-','linewidth',2.0);
%set(axh5, 'FontSize', 18);
subplot(3,2,6);
axh6 = axis();
chi2DistA = sort(chi2rnd(50, numPoints, 1));
h6chi2  = plot(chi2DistA, normalDist,'b-','linewidth',2.0);
%set(axh6, 'FontSize', 18);
clearvars chi2DistA;