close all;clear all;clc;
gap_length = 100e-9;
xpoints = linspace(0, gap_length, 1e4);
xpoints = xpoints.';
rho0 = ones(size(xpoints)) ./ gap_length;
diffFcn = @constantDiffusion;
driftFcn = @quadraticDrift;
time_Final = 1e-18;
[t, rho] = abm23_stepper(@(t,y)rhsFPE(t, y, xpoints, driftFcn, diffFcn, 1e19), [0 time_Final], rho0, 1e-6, 1e-5);
fh = figure(1);
ax = axes();
axis square;
plot(xpoints.', rho(end,:),'b-','linewidth',2.5);
xlabel('X');
ylabel('PDF');